import {makeStyles} from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  quantityRocker: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    flexShrink: 0,
    border: '1px solid',
    borderColor: theme.palette.text.secondary,
    boxShadow: theme.palette.shadows.paper,
    maxHeight: 25,
    width: 84,
    minWidth: 84,
    maxWidth: `84px !important`,
    zIndex: 2,
    background: theme.palette.background.default,
  },
  qty: {
    padding: '4px 10px',
    zIndex: 1,
    fontSize: 12,
    fontWeight: 600,
    color: theme.palette.text.themeRed,
    background: '#FFF8E2',
  },
  iconButton: {
    padding: 0,
    display: 'flex',
    alignSelf: 'center',
    width: 23,
    height: 23,
  },
  addButton: {
    padding: '0px 16px',
    border: '1px solid',
    borderColor: theme.palette.text.secondary,
    borderRadius: 4,
    boxShadow: theme.palette.shadows.paper,
    background: theme.palette.background.default,
    width: 86,
    maxWidth: 86,
    minWidth: 86,
    height: 25,
  },
  addText: {
    fontSize: 13,
    fontWeight: 500,
    verticalAlign: 'middle',
    color: theme.palette.text.themeRed,
    marginTop: -1,
  },
}));
