export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_LOADER = 'SET_LOADER';
export const SET_ERROR = 'SET_ERROR';

export const GET_GRAPH_DATA_CONFIRMED_PENDING =
  'GET_GRAPH_DATA_CONFIRMED_PENDING';
export const GET_GRAPH_DATA_CONFIRMED_SUCCESS =
  'GET_GRAPH_DATA_CONFIRMED_SUCCESS';
export const GET_GRAPH_DATA_CONFIRMED_FAILED =
  'GET_GRAPH_DATA_CONFIRMED_FAILED';

export const GET_API_STATUS_PENDING = 'GET_API_STATUS_PENDING';
export const GET_API_STATUS_SUCCESS = 'GET_API_STATUS_SUCCESS';
export const GET_API_STATUS_FAILED = 'GET_API_STATUS_FAILED';
